version: '3.7'
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: php737
    volumes:
      - ./app:/var/www
    ports:
      - 8000:80
  mysql:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./config/local.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 6033:3306
    volumes:
      - sample-dump:/var/lib/mysql
      - ./data/sample-dump.sql:/docker-entrypoint-initdb.d/sample-dump.sql
volumes:
  sample-dump:
