version: '3.7'
services:
  web:
    build:
      context: ./app/html
      dockerfile: Dockerfile
    container_name: php737
    volumes:
      - ./app:/var/www
    ports:
      - 8000:80
  mysql:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
    ports:
      - 6033:3306
    volumes:
      - sample-dump:/var/lib/mysql
      - ./data/sample-dump.sql:/docker-entrypoint-initdb.d/sample-dump.sql
volumes:
  sample-dump:
